### ISSUE TITLE
Unable to use named user methods if for iOS channel

### ISSUE THREAD

**Issue by connor-odoherty** [urbanairship/ruby-library#113]
The associate and disassociate methods on NamedUser return a 404 error because it impossible to set the device_type. The user passes in a device_type variable, but the code references a non-existent instance variable.

I have fixed this in my fork: https://github.com/connor-odoherty/ruby-library

**Comment by pdxmele** [comment]
Thanks for the report! I'm having a look at your PR and hope to have it merged in sometime tomorrow.

**Comment by pdxmele** [comment]
Merged in, gonna do a couple other small things and then do a new official release.
