### ISSUE TITLE
`Named_User#update_attributes` implementation

### ISSUE THREAD

**Issue by lloydwatkin** [urbanairship/ruby-library#129]
Hi,

I required this functionality, I have therefore implemented in a branch on [our](https://github.com/olioex) branch. It includes documentation. If you'd like me to make a pull request please let me know.

https://github.com/OLIOEX/ruby-library/tree/named-user-attributes

**Comment by pdxmele** [comment]
Please do PR this, thanks

**Comment by pdxmele** [comment]
Actually I should be able to pull into our dev repo to test and then do the other things I need to do before a new release, don't worry about it.

**Comment by pdxmele** [comment]
Released!
