### ISSUE TITLE
Custom Event code does not work/undocumented

### ISSUE THREAD

**Issue by lloydwatkin** [urbanairship/ruby-library#130]
**All bugs, feature requests, implementation concerns or general queries should be sent to our [support team](https://support.airship.com/).**

You are welcome to submit an issue here for bugs, but please also reach out to our support team as well.

Before completing the form below, please check the following:

- [x] You are using the most recent version of the library. 
- [x] You are using a supported version of Ruby for that library version. 
- [x] This issue is reproducible. 

## Expected Behavior
Custom event should be created on airship

## Current Behavior
Does not work.

Firstly it fails on authentication, because the event code forces the uses of 'bearer' auth type. If I remove this code I then receive the following error:

```javascript
{"ok":false,"operationId":"60645f1b-539a-4f2d-8d34-2b732dbf877e","error":"Malformed or missing header 'X-UA-Appkey: <appkey>'"}
```

## Possible Solution
Firstly remove `auth_type: :bearer` from  https://github.com/urbanairship/ruby-library/blob/main/lib/urbanairship/custom_events/custom_event.rb#L22. Then fix other bugs. Also please document the usage of this endpoint :)

## Steps to Reproduce
```ruby
client = Urbanairship::Client.new(key: ENV.fetch('AIRSHIP_APP_KEY'), secret: ENV.fetch('AIRSHIP_APP_SECRET'))
events = [{
  user: {
    named_user_id: named_user_id,    
  },
  body: {
    name: 'custom-event-send',
  },
}]
event = Urbanairship::CustomEvents::CustomEvent.new(client: AIRSHIP_CLIENT)
event.events = events
err = nil
begin
  event.create
rescue => error
  err = error
end
```

**Comment by lloydwatkin** [comment]
Closing, it seems this API requires a `bearer` style token with full access permissions.

**Comment by pdxmele** [comment]
Yep, we'll work on getting the example added to the API documentation though. Thanks!
