### ISSUE TITLE
Compatibility with API v3

### ISSUE THREAD

**Issue by nmondollot** [urbanairship/ruby-library#39]
Urbanairship introduced API v3 on 2013-07-22 :
http://docs.urbanairship.com/reference/api/v3/api-v3-migration-guide.html

V2 end of life scheduled for February 2014.
Any plans to make the gem work with v3?

We've been using urbanairship gem in production with great success, thanks to you guys! Keep up the great work!

**Comment by pdxmele** [comment]
Hi folks,
Mele from Urban Airship here. We're going to be turning off v1 support pretty soon now (July 31, 2015), and we're seeing if we have the resources to put together an official Ruby library soon. Please email support@urbanairship.com if you're interested to help us figure out where to prioritize the work. Thanks!

**Comment by trek** [comment]
@pdxmele we've been trying (without success) to find a new owner for this gem. We don't use Urban Airship via ruby any longer. Someone from Urban Airship even offered to follow up on taking it over #59, but that lead went dead. If you'd like to take it over, that'd be great. We still use Urban Airship in general, but are no longer the right owners for this code.

**Comment by dogweather** [comment]
Hi @trek. I commented back on the other issue about the library. Urban Airship has now decided to commit the resources to taking over ownership for this gem, and I'll be doing the transition. I'm excited to finally be able to move this forward.

**Comment by abedra** [comment]
@dogweather that's great news! We can initiate a transfer of the project if you like. Just let us know.

**Comment by dogweather** [comment]
@abedra Great. I just sent @trek an email: yes, please go ahead an initiate the transfer to the urban airship organization. I'll check and make sure it worked.

**Comment by abedra** [comment]
@dogweather It looks like I can't initiate the transfer request because I don't have rights to the urbanairship org. Is there a better way to do this or do I need temporary permission?

**Comment by dogweather** [comment]
Good question. I forked it to see what would happen, and that works fine, but it doesn't transfer the PR's and issues. I'll look into it more.

**Comment by dogweather** [comment]
@abedra Ok, github handles transfers differently depending on whether it's user-user or user-org.   Here's the easiest way for us: Transfer it to me (i.e., to my user account @dogweather); you should be able to do that. Then _I'll_ be able to transfer it to the urban airship organization account.

**Comment by abedra** [comment]
Ok thanks. I'll do that in a few.

**Comment by trek** [comment]
Looks like @abedra has it handled. Our only real ask is that you retain the "copyright Groupon" stuff in the license, adding your own name as desired. It should keep the lawyers happy.

**Comment by abedra** [comment]
@dogweather Ok I think I've got it. I had to transfer it to my personal account, then to you. What a mess this transfer business is. Let me know if it didn't work.

**Comment by trek** [comment]
Thanks for taking this over!

**Comment by dogweather** [comment]
You're welcome! Thanks for helping make the transition smooth. Nearly done.

**Comment by trek** [comment]
@dogweather is there an email we can use to transfer the gem ownership to you as well? http://guides.rubygems.org/command-reference/#gem-owner

**Comment by dogweather** [comment]
yes - robb.shecter@urbanairship.com. that's the email for the rubygems profile, https://rubygems.org/profiles/UrbanAirship

**Comment by dogweather** [comment]
Oh, it looks like you already got that. Excellent.

**Comment by pdxmele** [comment]
New release is out! Please let us know if you have any problems by emailing support@urbanairship.com. This version only supports pushy things so far, not device info, tagging, reports, etc., but feel free to submit requests for other features either to support or in the issues here.
