### ISSUE TITLE
make `do_request` public

### ISSUE THREAD

**Issue by shem8** [urbanairship/ruby-library#42]
Lib is great but missing lots of api features (for example- Individual device lookup: http://docs.urbanairship.com/reference/api/v3/device_information.html), what if you could build request from your own? 
Isn't will be better for users?

**Comment by pdxmele** [comment]
Hi, we're clearing all of these out now due to the rewrite. We'll be adding more stuff soon, which endpoints would you like us to support exactly? Please add them as individual issues by category if you would, or submit a ticket to support@urbanairship.com. Thank you!
