### ISSUE TITLE
add support for v3 scheduled notifications

### ISSUE THREAD

**Issue by brianatwhistle** [urbanairship/ruby-library#51]
Looks like the port to v3 is missing the ability to schedule a notification for the future.  In previous versions of the Urbanairship api, you would put a :schedule_for key into the normal push parameters.  Now you have to hit a separate API endpoint, /api/schedules.

http://docs.urbanairship.com/reference/api/v3/schedule.html

**Comment by pdxmele** [comment]
New release is out! Please let us know if you have any problems by emailing support@urbanairship.com. This version only supports pushy things so far, not device info, tagging, reports, etc., but feel free to submit requests for other features either to support or in the issues here.
