### ISSUE TITLE
Nil values in extra causes failure

### ISSUE THREAD

**Issue by jakecraige** [urbanairship/ruby-library#56]
If you send an extra value that is nil, the push fails. Not sure if this is intended

```ruby
    @notification = {
      apids: @android_tokens,
      android: {
        alert: @alert_message,
        extra: {
          title: @event_title # when nil, the request fails
        }
      }
    }
```

It's possible that other places do this instead but this is just the one I noticed. It may not be the gem's job to check this but I wanted to point it out. At least some sort of error that gives insight as to what's going on would be helpful

**Comment by pdxmele** [comment]
Hi, we're clearing all of these out now due to the rewrite. If you run into any problems, please email support@urbanairship.com. Thank you!
