### ISSUE TITLE
V3 status?

### ISSUE THREAD

**Issue by epinault** [urbanairship/ruby-library#77]
So I see the README was updated on April 20th.. And it seems to mention that V3 is not yet supported.. What I am confused is that V3 exists singe July 2014 and the gem was never updated. Now V1 is being retired so does that mean the gem in the current state does not work?

Can you please confirm that V3 will or will not work in its latest version? i see a lot of pull request but hard to tell the state of this project at this point of time

**Comment by pdxmele** [comment]
Hi! UA just recently took over ownership of this repo and we're currently working on a full rewrite for v3 (but it has not been shipped yet). I'll add a note to the top of the readme to hopefully help clear this up. I'm not sure about the current state of the code.

**Comment by epinault** [comment]
Thanks for the update! Any idea how long before V3 ships ?

**Comment by pdxmele** [comment]
Sorry, no ETA at the moment. We're going to do our best to get it out quickly, but we don't actually have many Rubyists on staff. Thanks for your patience!

**Comment by readysetawesome** [comment]
Please update your README. The assertions it made about v3 supported sent me in the wrong direction for a while.

**Comment by epinault** [comment]
You can use V3 by the way with the current state. I found a way to do it

**Comment by bswinnerton** [comment]
Care to expand @epinault? I'm sure lots of people are interested.

**Comment by epinault** [comment]
Yes! sorry forgot to add the code yesterday . Notice the Message structure for V3 and the version: 3 specified . That should d it. That gem is really a pass through in some ways


````
     notification = { 
       version: 3,
       audience: { 
         tag: tags # can be one tag as a string or a list as an array
       }, 
       notification: {
           alert: message,
           ios: {
             extra: { digest: extra}
           },
           android: { 
             extra: { digest: extra}
            } 
          },  
        device_types: "all" 
       }
Urbanairship.push(notification)
````

**Comment by pdxmele** [comment]
New release is out! Please let us know if you have any problems by emailing support@urbanairship.com. This version only supports pushy things so far, not device info, tagging, reports, etc., but feel free to submit requests for other features either to support or in the issues here.
