### ISSUE TITLE
Wait for V3 or use Dirigible?

### ISSUE THREAD

**Issue by hartator** [urbanairship/ruby-library#79]
Thanks for the awesome work,

I wonder what you guys official recommendation concerning V3 support? 

Should we wait for you guys to release the ruby v3 wrapper or should we use another gem like Dirigible (https://github.com/anthonator/dirigible) in the meantime?

We are concerned because of the July 31th deadline we receive to upgrade to v3.

**Comment by pdxmele** [comment]
Hi,

Thank you for being patient with us while we try to get this done in time. We unfortunately had some resource changes that we weren't anticipating that have slowed things down.

Please feel free to use whatever library or tools you like to help with your v3 transition (or write your own), and rely on our official API docs when you run into any problems: http://docs.urbanairship.com/api/ua.html .

Also, please note that v1/v2 support is only being turned off for the push and scheduled push endpoints, so those are really all you need to worry about right now.

Thanks!

**Comment by hartator** [comment]
Hey, pdxmele, duly noted, thanks for the response, appreciate it.

**Comment by pdxmele** [comment]
New release is out! Please let us know if you have any problems by emailing support@urbanairship.com. This version only supports pushy things so far, not device info, tagging, reports, etc., but feel free to submit requests for other features either to support or in the issues here.
