### ISSUE TITLE
Urban airship is indirectly depending on insecure version of rest-client through unirest dependency

### ISSUE THREAD

**Issue by paneq** [urbanairship/ruby-library#86]
* https://github.com/Mashape/unirest-ruby/issues/24

It would be nice to help `Mashape` to upgrade to newest version of `rest-client`

**Comment by justinsoong** [comment]
This is kinda of an issue huh

**Comment by noam87** [comment]
is unirest being actively maintained? I see two unmerged PRs about this issue... it's also causing dependency issues.

**Comment by philtr** [comment]
Hey, didn't even see this. I just submitted #94 to remove the Unirest dependency.

**Comment by nastia-shaternik** [comment]
hey @philtr 

what's the problem that your PR is not in master now?

**Comment by philtr** [comment]
@nastia-shaternik if I remember correctly it didn't handle error responses quite as gracefully as Unirest. I was trying to use Net::HTTP instead. It would probably be a lot easier to move to RestClient instead if you want to take a stab at that. IMO API wrappers should use Net::HTTP, but I didn't have time to debug.

**Comment by pdxmele** [comment]
This is now fixed, thanks for the report!
