### ISSUE TITLE
Add support for named_user as an audience

### ISSUE THREAD

**Issue by nickhammond** [urbanairship/ruby-library#91]
http://docs.urbanairship.com/api/ua.html#audience-selectors

**Comment by jkvoorhis** [comment]
Hey @nickhammond,

Please feel free to submit a PR adding a Named User Audience Selector following our Contributor guidelines https://github.com/urbanairship/ruby-library#contributing. Otherwise we will add it in when we have our next release.

**Comment by sahild** [comment]
Please merge this pull request.

**Comment by MixedRice** [comment]
+1
