### ISSUE TITLE
References to log file held

### ISSUE THREAD

**Issue by rohanpatel2602** [urbanairship/ruby-library#97]
I'm seeing multiple references being held to the urbanairship.log everytime I send a message via urbanairship.

If I run `lsof` towards the end of the day I see hundreds of references to the log.

Is this an issue with the gem or something on my boxes themselves?

Example:
``ruby       4732       root  551w      REG              202,1     5231695     427587 /shoto/shared/log/urbanairship.log``

**Comment by madelgi** [comment]
Hey @rohanpatel2602, this was totally an issue on our end. We patched the library today – you can get the latest version (3.2.2) at [rubygems](https://rubygems.org/gems/urbanairship/versions/3.2.2). Thanks for bringing this to our attention!

**Comment by rohanpatel2602** [comment]
@madelgi Thank you for the prompt reply and patch!

**Comment by rohanpatel2602** [comment]
@madelgi 
It actually doesn't seem to be resolved :(
Updated the gem on all my boxes but just noticed that it still seems to be occuring

**Comment by madelgi** [comment]
Hey @rohanpatel2602 – I'm sorry to hear that. If you happened to record it, do you mind telling me how many references you saw yesterday, and how many you see now, with the new patch? Are the numbers significantly different, or has there been virtually no change? If there are any particular details about your setup that may help diagnose the issue, feel free to share them with us.

I'll try and see if I can get to the bottom of this, as time permits. In the meantime, If you think you have a fix, you're welcome to submit a PR.

**Comment by rohanpatel2602** [comment]
@madelgi 
It seemed to be the same number of references that we were seeing on version 3.0.2 of the gem
I'm a little confused as well as a cursory glance of the patch you submitted does look like it would fix the issue!

I'll try to dig into it a bit more myself and get back to you
