### ISSUE TITLE
Uncaught exception: wrong number of arguments (1 for 0)

### ISSUE THREAD

**Issue by rotem443** [urbanairship/ruby-library#98]
This is my code:
`
		class NotficationHandler
		require 'urbanairship'
		UA = Urbanairship

		airship = UA::Client.new(key:'Censored', secret:'Censored')
		
		def self.schedule_notfication(segment, message, time)
			push = airship.create_push
			push.audience = UA.segment(segment)
			push.notification = UA.notification(alert: message)
			push.device_types = UA.all
			push.schedule = UA.scheduled_time(time)
			push.send_push
		end

		def self.get_segment_list()
			return UA::SegmentList.new(client: airship)
		end
	end
`

The error is occur after the initialize of airship (UA::Client.new). 
What i am doing wrong?

**Comment by pdxmele** [comment]
Hey there, instead of troubleshooting this in Github I think our support system & team will be able to be more helpful. Please reach out to them via https://support.urbanairship.com / support@urbanairship.com .
