### ISSUE TITLE
Schedule notification arrives with no message

### ISSUE THREAD

**Issue by rotem443** [urbanairship/ruby-library#99]
I checked out the logs and this is how the request looks like :

{"schedule":{"scheduled_time":"2016-08-24T05:00:00"},"push":{"audience":{"segment":"*Censorship*"},"notification":{"ios":{"alert":"message12","badge":"+1","sound":"default","extra":{"featured":"10"}}},"device_types":["ios"]}}

What should i do ?

**Comment by pdxmele** [comment]
This doesn't look like an issue with the library itself, so please contact our support team at https://support.urbanairship.com and they'll be happy to help you out!
